# -*- coding: utf-8 -*-
"""Handwriting Recognition

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Toh3a2ARLo35US9fBeniaQwWePCQfevm
"""

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd
import pylab as pl

from sklearn.datasets import load_digits

df=load_digits()

#displaying the first image
pl.gray()
pl.matshow(df.images[0])
pl.show()

df.images[1]

imagesandlables=list(zip(df.images,df.target))
plt.figure(figsize=(5,5))

n_samples=len(df.images)
print(n_samples)

X=df.images.reshape(n_samples,-1)
y=df.target

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y)

print(X_train.shape)

print(y_train.shape)

#SVC
from sklearn.svm import SVC

classifier=SVC(kernel='linear',random_state=0)
classifier.fit(X_train,y_train)

y_pred=classifier.predict(X_test)

classifier.score(X_train,y_train)

classifier.score(X_test,y_test)

#input image
selected_image = df.images[0]

selected_image = selected_image.reshape(1, -1)

predicted_label = classifier.predict(selected_image)

print('Predicted digit:', predicted_label)

selected_image1 = df.images[1]
selected_image1 = selected_image1.reshape(1, -1)

predicted_label1 = classifier.predict(selected_image1)
print('Predicted digit1:', predicted_label1)

selected_image2 = df.images[15]
selected_image2= selected_image1.reshape(1, -1)

predicted_label2 = classifier.predict(selected_image2)
print('Predicted digit:', predicted_label2)

images = df.data
labels = df.target

first_10_image_labels = labels[:20]
print(f"Labels for the first 20 images: {first_10_image_labels}")

